package com.xiaoguo.memo.dao.mapper;

import com.xiaoguo.memo.dao.dataobj.MemoDO;
import com.xiaoguo.memo.dao.dataobj.MemoDOParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    long countByExample(MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int deleteByExample(MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int insert(MemoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int insertSelective(MemoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    List<MemoDO> selectByExampleWithBLOBs(MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    List<MemoDO> selectByExample(MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    MemoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByExampleSelective(@Param("record") MemoDO record, @Param("example") MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") MemoDO record, @Param("example") MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByExample(@Param("record") MemoDO record, @Param("example") MemoDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByPrimaryKeySelective(MemoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(MemoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_memo
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByPrimaryKey(MemoDO record);
}