package com.xiaoguo.memo.dao.mapper;

import com.xiaoguo.memo.dao.dataobj.UserDO;
import com.xiaoguo.memo.dao.dataobj.UserDOParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    long countByExample(UserDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int deleteByExample(UserDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    List<UserDO> selectByExample(UserDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByExampleSelective(@Param("record") UserDO record, @Param("example") UserDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByExample(@Param("record") UserDO record, @Param("example") UserDOParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xg_user
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    int updateByPrimaryKey(UserDO record);
}