package com.xiaoguo.memo.dao.dataobj;

import java.util.Date;

public class MemoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.title
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.user_id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_memo.content
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.id
     *
     * @return the value of xg_memo.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.id
     *
     * @param id the value for xg_memo.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.gmt_create
     *
     * @return the value of xg_memo.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.gmt_create
     *
     * @param gmtCreate the value for xg_memo.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.gmt_modified
     *
     * @return the value of xg_memo.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.gmt_modified
     *
     * @param gmtModified the value for xg_memo.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.title
     *
     * @return the value of xg_memo.title
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.title
     *
     * @param title the value for xg_memo.title
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.user_id
     *
     * @return the value of xg_memo.user_id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.user_id
     *
     * @param userId the value for xg_memo.user_id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.status
     *
     * @return the value of xg_memo.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.status
     *
     * @param status the value for xg_memo.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_memo.content
     *
     * @return the value of xg_memo.content
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_memo.content
     *
     * @param content the value for xg_memo.content
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}