package com.xiaoguo.memo.dao.dataobj;

import java.util.Date;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.user_name
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.password
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xg_user.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.id
     *
     * @return the value of xg_user.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.id
     *
     * @param id the value for xg_user.id
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.gmt_create
     *
     * @return the value of xg_user.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.gmt_create
     *
     * @param gmtCreate the value for xg_user.gmt_create
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.gmt_modified
     *
     * @return the value of xg_user.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.gmt_modified
     *
     * @param gmtModified the value for xg_user.gmt_modified
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.user_name
     *
     * @return the value of xg_user.user_name
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.user_name
     *
     * @param userName the value for xg_user.user_name
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.password
     *
     * @return the value of xg_user.password
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.password
     *
     * @param password the value for xg_user.password
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xg_user.status
     *
     * @return the value of xg_user.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xg_user.status
     *
     * @param status the value for xg_user.status
     *
     * @mbg.generated Sat Apr 19 20:21:04 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}